version: '2'
services:
    carpoolingcsid2016-mysql:
        container_name: carpoolingcsid2016-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/CarpoolingCSID2016/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=carpoolingcsid2016
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
